### ISSUE TITLE
Broken link to download URL for pretrained models

### ISSUE THREAD

**Issue by PINTO0309** [kyotovision-public/dynamic-3d-gaze-from-afar#1]
Thank you for sharing your wonderful repository with us. The link in the URL below appears to be corrupted. If it is not too much trouble, could you please correct the link?
https://github.com/kyotovision-public/dynamic-3d-gaze-from-afar#evaluation-with-the-gafa-dataset
![image](https://user-images.githubusercontent.com/33194443/168827516-81683a33-cf94-4c84-8b0c-f18c30f55411.png)

**Comment by nbhr** [comment]
Hi, thank you for pointing this out.   We have updated `README.md` and now you can download `gazenet_GAFA.pth` from the link.

**Comment by PINTO0309** [comment]
I have checked. Thanks for your quick response! :smile_cat:
