### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [kyotovision-public/dynamic-3d-gaze-from-afar#3]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

- Model Zoo
https://github.com/PINTO0309/PINTO_model_zoo

- ONNX converted GazeNet (GAFA only)
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/297_GazeNet

Thank you.

**Comment by nbhr** [comment]
Thanks.  It is MIT.  We added `LICENSE` file in the repositry.

**Comment by PINTO0309** [comment]
Thank you! 

I have verified that it is committed to the development branch. :smile:
