### ISSUE TITLE
The positions of head and body in GAFA dataset

### ISSUE THREAD

**Issue by Matus-Tanonwong** [kyotovision-public/dynamic-3d-gaze-from-afar#5]
Hi, there!!
Thank you very much for your great work! It is very interesting.
I have one question about the positions of head and body in GAFA dataset.
Are they in the camera coordinate system or the world coordinate system?
I have been trying the plot an output of the gaze estimation on an image in **demo.ipynb**, but cannot find the correct position of the person's head center.
Could you please give me some guidance?
Thank you very much in advance for your consideration.

**Comment by SomaNonaka** [comment]
Thank you for your interest!
The 3D positions of head and body are provided in the camera coordinate system. 
If you only need 2D head and body positions, you can use the 2D body keypoints detected with OpenPose, which are stored in the same file. https://github.com/kyotovision-public/dynamic-3d-gaze-from-afar/blob/7d7debdc527153ab63a6b3905311267f9a62e399/data/preprocessed/preprocess.py#L32

**Comment by Matus-Tanonwong** [comment]
Thank you very much for your kind response!!
It works.
