### ISSUE TITLE
GAFA dataset omission

### ISSUE THREAD

**Issue by Aiden-0209** [kyotovision-public/dynamic-3d-gaze-from-afar#9]
Hi, there :)
Thank you very much for your great work! I like your great work.
I have one question about the GAFA dataset.

I downloaded the dataset and checked it.
I think the key point is missing, but I wonder if I checked it wrong.
Some key points point to (0,0,0).

especially 0, 15, 16 keypoint is often (0,0,0)

example file
![image](https://user-images.githubusercontent.com/88304611/213380874-b01f0a1e-1050-48dd-896b-754cd9f6a3a0.png)

**Comment by SomaNonaka** [comment]
Hi,
A keypoint with the value (0,0,0) means that the body joint could not be found in the image. The 0,15,16 keypoint corresponds to nose and both eyes, and these joints are occluded when the person is facing away from the surveillance camera, so they often get (0,0,0).
